[Feature] debug
ROBOTIS-move/labelme pull request #109
Opened 2024-02-27 07:58 UTC by DongyunRobotis

특정 PC에서 발생하는 버그 수정
- Config File 읽을 때 utf-8로 코덱을 지정하여 읽을 수 있도록 수정
- worker_name 파일 읽을 때 os 환경에 따라서 '/', '\\' 를 선택해서 사용하도록 수정

Indoor 작업에서 Point size가 지나치게 작던 부분 수정

2024-02-27 08:54 UTC, MilyangParkJaeHun commented on labelme/widgets/worker_name_dialog.py
> +        with open(sys.path[0] + self.split_char +'worker_name.txt', "a") as f:
os 마다 경로 구분자가 다른 문제는 os.path.join 을 사용하면 해결이 안되나요?
```suggestion
        with open(os.path.join(sys.path[0], 'worker_name.txt'), "a") as f:
```

2024-02-27 22:31 UTC, DongyunRobotis commented on labelme/widgets/worker_name_dialog.py
> +        with open(sys.path[0] + self.split_char +'worker_name.txt', "a") as f:
그 방법이 있었군요~! 반영 완료했습니다
감사합니다~!

2024-02-27 22:55 UTC, HunJ93 approved these changes
확인했습니다

2024-02-27 23:38 UTC, jongsuff requested changes
path 구문자를 윈도우에서는 `\\`로 설정해주면 문제 없을것이라 생각했는데 문제가 생겼었나보네요~
함수 사용 방법에 문제가 있는것 같아 수정 요청 드립니다!

2024-02-27 23:38 UTC, jongsuff commented on labelme/utils/measure_working_time.py
> +        self.name_file_path = os.path.join(sys.path[0] + 'worker_name.txt')
```suggestion
        self.name_file_path = os.path.join(sys.path[0], 'worker_name.txt')
```
`os.path.join()` 함수 용법은 `+`로 더하는것이 아니라 path 합성하고 싶은 인자들을 `,`로 구분하여 여러 개 넣는 것으로 알고있습니다~

2024-02-27 23:38 UTC, jongsuff commented on labelme/utils/measure_working_time.py
> +        with open(os.path.join(folder_path + 'Cache.txt'), "a") as f:
여기도 위 코멘트와 마찬가지입니당

2024-02-27 23:38 UTC, jongsuff commented on labelme/widgets/worker_name_dialog.py
> +        with open(os.path.join(sys.path[0] + 'worker_name.txt'), "a") as f:
여기도요!

2024-02-28 00:58 UTC, DongyunRobotis commented on labelme/utils/measure_working_time.py
> +        self.name_file_path = os.path.join(sys.path[0] + 'worker_name.txt')
헛.. 수정 완료했습니다~!

2024-02-28 00:59 UTC, MilyangParkJaeHun approved these changes
작업 수고하셨습니다!

2024-02-28 04:40 UTC, jongsuff approved these changes
수고 많으셨습니다!

2024-02-28 04:40 UTC, merged