Added editing bounding box size with top right and bottom left corner and fixed bug in measuring working time
ROBOTIS-move/labelme pull request #113
Opened 2024-03-10 23:19 UTC by jongsuff

### 새로운 기능 추가: 박스 수정 꼭짓점 추가
- 기능 추가 요청사항(https://github.com/ROBOTIS-move/labelme/issues/110)에 대응하기 위한 작업을 진행했습니다.
- 기존에 박스를 수정할 때 박스 꼭짓점들 중 `좌상단/우하단` 꼭짓점만 수정가능한 상태였으나, `우상단/좌하단` 꼭짓점으로도 수정할 수 있도록 기능을 추가했습니다.
- 새로운 `우상단/좌하단` 꼭짓점은 박스 수정시에만 사용되며, json파일 내 데이터는 기존과 동일하게 `좌상단/우하단` 좌표만 저장됩니다.

### 작업 시간 버그 수정
- 계산된 라벨러 작업 시간이 저장되는 cache파일에 작업자 이름에 대한 정보가 누락되어 해당 정보를 저장하는 기능을 추가하였습니다(by @DongyunRobotis).
- 라벨러 작업 시간 계산에 microsecond까지 계산되도록 수정하였습니다(by @DongyunRobotis).

2024-03-10 23:24 UTC, DongyunRobotis approved these changes
확인 완료했습니다~!
고생하셨습니다~!

2024-03-11 00:07 UTC, MilyangParkJaeHun approved these changes
디텍션 라벨링 기능 추가 확인하였습니다.
작업 수고하셨습니다!

2024-03-11 06:41 UTC, HunJ93 approved these changes
확인했습니다.
고생하셨습니다.

2024-03-12 00:14 UTC, pung87 requested changes

2024-03-12 00:14 UTC, pung87 commented on labelme/app.py
> +                shape.align_points()
함수 네이밍에서 스네이크케이스가 부분 존재하는데, 한번 확인해주세요.

2024-03-12 00:14 UTC, pung87 commented on labelme/utils/measure_working_time.py
>          if diff_interaction_time < 0 :
0과 : 사이의 공백 확인 바랍니다.

2024-03-12 01:23 UTC, jongsuff commented on labelme/app.py
> +                shape.align_points()
함수 네이밍에 스네이크케이스는 기존 오픈소스 코드와의 통일성을 위해 의도적으로 작성하였습니다.
모든 함수 네이밍을 변경하기에는 변경사항이 너무 많아서요 ㅎㅎ

2024-03-12 01:26 UTC, jongsuff commented on labelme/utils/measure_working_time.py
>          if diff_interaction_time < 0 :
@DongyunRobotis 이 부분은 제가 수정하였습니다~
[3c2c169](https://github.com/ROBOTIS-move/labelme/pull/113/commits/3c2c169134e8d2f977dcaa04bf1af86f105a47a2)

2024-03-12 01:45 UTC, jongsuff commented
- 기존에 박스 좌표가 추가될 때 `[먼저 찍은 포인트, 나중에 찍은 포인트]` 형식으로 저장되어 학습 데이터 생성 시 버그가 발생하였다는 리폿을 받았습니다 (by @DongyunRobotis)
- 해당 이슈에 대응하기 위해 현 PR에서 박스 포인트를 정렬하는 기능을 추가했습니다([4e973e9](https://github.com/ROBOTIS-move/labelme/pull/113/commits/4e973e9c4d90368601b6848e8851f8dd34b9e1ad))

2024-03-12 02:09 UTC, pung87 commented on labelme/app.py
> +                shape.align_points()
아 그렇군요! 알겠습니다 ㅎㅎ 히스토리 이해가 부족했습니다. 고생하셨습니다!

2024-03-12 02:10 UTC, pung87 approved these changes
확인했습니다. 고생하셨습니다!

2024-03-12 02:10 UTC, merged