Feature add version checker
ROBOTIS-move/labelme pull request #120
Opened 2024-07-14 23:34 UTC by DongyunRobotis

**기능 추가 및 개선**

**1. Labelme 최신 버전 체크 기능**
- 동작 방식: Labelme GitHub develop repository에서 version.xml 파일을 읽어와 현재 로컬에 설치된 Labelme의 version.xml 파일 버전과 비교합니다.
- 버전 불일치 시: Version Checker 팝업이 활성화되며, 확인 버튼을 누르면 Labelme가 종료되어 추가 작업이 불가능합니다.
- 인터넷 미연결 시: 인터넷 연결을 요청하는 팝업이 활성화됩니다.

**2. 작업량 로그 저장 시점 추가**
- 이전 이미지로 돌아가서 작업하는 경우: 해당 시점의 작업량 로그를 저장합니다.
- 작업 도중 Labelme 프로그램을 종료하는 경우: 프로그램 종료 시점의 작업량 로그를 저장합니다.

* 참고사항
 - 테스트를 위해서 **labelme/utils/version_checker.py** 파일에서 self.url = 'https://raw.githubusercontent.com/ROBOTIS-move/labelme/**develop**/version.xml' 코드에서 develop 부분을 **feature-add-version-checker**로 변경해주시면 됩니다.

2024-07-16 04:51 UTC, HunJ93 approved these changes

2024-07-16 07:54 UTC, jongsuff requested changes
버전 체크 기능 추가 확인했습니다! 테스트 해보니 잘 동작하네요 ㅎㅎ
라벨러분들의 업데이트 누락을 방지할 수 있는 좋은 방법인것 같습니당
몇몇 수정사항 요청드립니다.

2024-07-16 07:54 UTC, jongsuff commented on labelme/utils/measure_working_time.py
> +            print(description_text)
잊지말고 꼭 지워주십쇼!

2024-07-16 07:54 UTC, jongsuff commented on labelme/widgets/invalid_version_popup.py
> +                f'!!! 버전 정보가 맞지 않습니다. !!!\n 최신 버전을 다운로드 해주세요.\n현재 버전 : {local_version}, 최신 버전 : {github_version}']}
100칸 안넘게 부탁드립니다

2024-07-16 23:54 UTC, DongyunRobotis commented on labelme/app.py
> +            version_popup = InvalidVersionWindow(1, version_checker.local_version, version_checker.github_version)
수정해서 반영 했습니다~!

2024-07-16 23:54 UTC, DongyunRobotis commented on labelme/cli/draw_object_label.py
> +                if not popup is None:
수정해서 반영 했습니다~!

2024-07-16 23:56 UTC, DongyunRobotis commented on labelme/shape.py
> +                        x_offset = int(len(self.label) * 0.5 * self.label_font_size * 0.8)
0.5는 Text의 센터
0.8은 글자 폰트를 기준으로 가로 사이즈 0.8배로 설정해둔 부분이라서
합쳐서할 경우 나중에 수정하기 힘들 것 같아서 따로 변수명을 지정해서 수정하였습니다~! 

```
text_center_ratio = 0.5
                        text_width_ratio = 0.8
                        x_offset = int(
                            len(self.label) * text_center_ratio * self.label_font_size * text_width_ratio)
```

2024-07-16 23:57 UTC, DongyunRobotis commented on labelme/utils/measure_working_time.py
> +    def __init__(self, crypto_mode = False):
공백 제거 완료했습니다~!

2024-07-17 00:20 UTC, jongsuff approved these changes
코멘트 반영 감사합니당
구두로 이야기 나누었듯이 다음부터는 GPG key 세팅 확인 부탁드립니다!
수고하셨습니당

2024-07-17 00:34 UTC, MilyangParkJaeHun approved these changes
버전 체크 기능과 라벨 이름 시각화 작업 확인하였습니다.
라벨미 업데이트 공지시에 라벨 이름 시각화 된 부분 활성/비활성 버튼에 대한 안내도 같이 있으면 좋을 것 같습니다.
작업 수고하셨습니다!

2024-07-29 02:47 UTC, closed without merging