Feature version checker
ROBOTIS-move/labelme pull request #122
Opened 2024-07-29 02:43 UTC by DongyunRobotis

2024-07-31 23:36 UTC, kjwoo31 approved these changes

2024-08-01 00:13 UTC, MilyangParkJaeHun commented
@DongyunRobotis 저번에 close 된 PR 과 아예 동일한 내용의 PR 인가요? 리뷰를 다시 진행해야하는지 해서요

2024-08-01 00:17 UTC, jongsuff commented
@kjwoo31 님 리뷰시에는 코멘트 남겨주셔야합니다~

2024-08-01 00:18 UTC, jongsuff commented
> 4. Drawing 관련 수정
실내 라벨링 중 Polygon과 Box 데이터가 공존하는 경우 둘다 그리기 및 수정이 가능합니다.
@MilyangParkJaeHun 님 위 부분이 추가된것 같네요

2024-08-01 00:29 UTC, DongyunRobotis commented
@MilyangParkJaeHun 
네 동일한 PR이기는 하지만 @jongsuff 님께서 말씀하신 부분이 추가 되었습니다.
혹시나 실외 Segmentation 이미지를 라벨링하실 때 정상적으로 추가 및 삭제가 되는지 확인해주시면 될 것 같습니다.

2024-08-01 00:49 UTC, jongsuff requested changes
새롭게 추가된 polygon + rectangle 모드 확인했습니다.
실외 세그맨테이션 데이터로도 테스트 부탁드립니다~
수정 요청사항 코멘트 남겼습니다.

2024-08-01 00:49 UTC, jongsuff commented on labelme/app.py
> +                    self.actions.createRectangleMode.setEnabled(False)
```suggestion
                enable_drawing_polygon = self._classType is None or 'segmentation' in self._classType
                enable_drawing_rectangle = self._classType is None or 'detection' in self._classType
                self.actions.createRectangleMode.setEnabled(enable_drawing_rectangle)
                self.actions.createMode.setEnabled(enable_drawing_polygon)
```
위에서 구현하셨던것과 비슷하게 해도 되지 않을까요?

2024-08-01 00:49 UTC, jongsuff commented on labelme/app.py
> +            if len(shape.points) == 2:
밑에 좌표정렬과 코너 업데이트하는 구문이 있는데 detection조건 빠져도 정상작동 하나요?
실외 세그맨테이션 데이터로 테스트 해보셨나요?

2024-08-01 00:53 UTC, kjwoo31 approved these changes
확인하였습니다. 고생하셨습니다.

2024-08-01 01:03 UTC, DongyunRobotis commented on labelme/app.py
> +            if len(shape.points) == 2:
detection 외에 Segmentation은 점 개수가 3개 이상 찍히지 않으면 Polygon 데이터가 생성이 되지 않더라구요
shape.points == 2개인 경우는 항상 detection인 경우만 발생하기 때문에 제외시켰습니다~!

2024-08-01 01:08 UTC, jongsuff commented on labelme/app.py
> +            if len(shape.points) == 2:
오 그러네요 ㅎㅎ 당연한 내용이었군요!

2024-08-01 04:39 UTC, DongyunRobotis commented on labelme/app.py
> +                    if self._classType is None or 'detection' in self._classType:
이게 통일하려고 했는데 labelme 처음 제작했던 때부터 있던거라서 app.py에만 900개 이상에 ""가 사용되어서 전체를 수정하는게 쉽지 않네요... 
flake8 lint에서 에러가 발생하지는 않습니다

2024-08-02 05:40 UTC, MilyangParkJaeHun reviewed
기능 추가 수고하셨습니다 ㅎㅎ
세그멘테이션 문제없이 라벨링 되는 것 확인하였습니다.
코멘트 하나 확인 부탁드립니다!

2024-08-02 05:40 UTC, MilyangParkJaeHun commented on labelme/utils/version_checker.py
> +                print('INTERNET CONECTION Fail')
오타 있는 것 같습니다
```suggestion
                print('INTERNET CONNECTION Fail')
```

2024-08-06 08:47 UTC, merged